#!/usr/bin/env python3
"""Iterative self-play training loop for Orion.

Starts from EITHER an existing model (generation 1 generates fresh data from it)
OR an existing training dataset (generation 1 skips generation and trains
directly on the supplied data). All subsequent generations are full
generate → train → evaluate loops gated by a win-rate threshold vs. the current
champion.

All outputs for this run land under RUN_DIR (created if missing): generated
training data under RUN_DIR/trainingdata/, saved models under RUN_DIR/models/,
per-call reports as RUN_DIR/gen_NN_*.json, and the master aggregate as
RUN_DIR/run.json. The master file is rewritten atomically after every generation.

Exactly one of --initial-model or --initial-data must be supplied.

Usage:
   iterative_gameplay.py RUN_DIR (--initial-model PATH | --initial-data PATH) [options]

Options:
   --initial-model PATH        Initial model to start self-play from (gen 1 begins with generate)
   --initial-data PATH         Initial training data to start from (gen 1 begins with train; skip generate)
   --games-per-generation N    Games to generate per generation                  [default: 5000]
   --epochs N                  Training epochs per generation                    [default: 100]
   --training-batch-size N     Training batch size                               [default: 256]
   --generate-batch-size N     Games to run in parallel during MCTS generation   [default: 128]
   --generations N             Total number of generations to run                [default: 15]
   --eval-games N              Games to play when evaluating                     [default: 500]
   --champion-threshold N      Min win rate vs previous to accept new model (0=off)   [default: 0.52]
   --early-stopping N          Stop training after N epochs w/out improvement (0=off) [default: 10]
   --initial-temp TEMP         Sampling temperature for generation 1             [default: 1.5]
   --final-temp TEMP           Sampling temperature for the last generation      [default: 0.5]
   --learning-rate R           Learning rate for generation 1                    [default: 0.0003]
   --lr-decay R                Multiplicative LR decay per generation (1.0 = no decay) [default: 0.95]
   --weight-decay N            Weight decay rate                                 [default: 0.0]
   --eval-temp TEMP            Sampling temperature during evaluation (0=greedy) [default: 0.1]
   --dropout N                 Dropout rate for trunk layers (0=disabled)        [default: 0.1]
   --monte-carlo-samples N     MCTS monteCarloSamples per move (0=disabled)      [default: 25]
   --mcts-leaf-batch N         Leaves selected per MCTS round via virtual loss   [default: 8]
   --c-puct N                  MCTS exploration constant                         [default: 1.5]
   --accumulate-data           Train on all previous generations' data, not just the latest
   --binary PATH               Path to the orion binary                          [default: .build/release/orion]
   -h --help                   Show this help message
"""

import datetime
import json
import os
import subprocess
import sys
from dataclasses import dataclass, asdict
from typing import Optional

from docopt import docopt


# ── Terminology ───────────────────────────────────────────────────────────────
#
#  Step       — one forward+backward pass through a single batch of training examples.
#  Epoch      — one full pass through the current training dataset (many steps).
#  Generation — one full generate → train → evaluate round orchestrated by this
#               script (many epochs). The model improves; the next generation's data
#               is generated by the updated model. A run produces a lineage of N
#               models, one per accepted generation.
#
# ── Configuration ─────────────────────────────────────────────────────────────

@dataclass
class Config:
   runDir:              str
   initialModel:        Optional[str]
   initialData:         Optional[str]
   gamesPerGeneration:  int
   epochs:              int
   trainingBatchSize:   int
   generateBatchSize:   int
   maxGenerations:      int
   evalGames:           int
   championThreshold:   float
   earlyStopping:       int
   initialTemp:         float
   finalTemp:           float
   learningRate:        float
   lrDecay:             float
   weightDecay:         float
   evalTemp:            float
   dropout:             float
   monteCarloSamples:   int
   mctsLeafBatch:       int
   cPuct:               float
   accumulateData:      bool
   binary:              str


# ── Shell helpers ──────────────────────────────────────────────────────────────

_command_log: Optional[str] = None   # set in main()

BOLD_CYAN  = "\033[1;36m"
RESET      = "\033[0m"

def _logCommand (args: list[str], suffix: str = ""):
   """Print command prominently and append to the command log."""
   cmd = " ".join(args) + (f"  {suffix}" if suffix else "")
   print(f"\n{BOLD_CYAN}▶ {cmd}{RESET}")
   if _command_log:
      with open(_command_log, "a") as f:
         f.write(cmd + "\n")


def writeJsonAtomic (path: str, obj) -> None:
   """Atomic JSON write: temp file + rename."""
   os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
   tmp = path + ".tmp"
   with open(tmp, "w") as f:
      json.dump(obj, f, indent=2, sort_keys=True)
   os.replace(tmp, path)


def readJson (path: str) -> dict:
   with open(path) as f:
      return json.load(f)


def runOrion (args: list[str], label: str, reportPath: str) -> Optional[dict]:
   """Run an orion subcommand with --report-json and return the parsed report dict.
   Returns None if the subprocess failed or didn't produce the report file."""
   fullArgs = args + ["--report-json", reportPath]
   _logCommand(fullArgs)
   result = subprocess.run(fullArgs)
   if result.returncode != 0:
      print(f"[ERROR] '{label}' exited with code {result.returncode}", file=sys.stderr)
      return None
   if not os.path.exists(reportPath):
      print(f"[ERROR] '{label}' did not produce report at {reportPath}", file=sys.stderr)
      return None
   return readJson(reportPath)


# ── Step functions (each returns the structured report dict, or None on failure) ─

def generateData (cfg: Config, outputPath: str, agent: str, temperature: float, reportPath: str) -> Optional[dict]:
   args = [
      cfg.binary, "generate",
      "-o", outputPath,
      "-n", str(cfg.gamesPerGeneration),
      "-a", agent,
      "-t", f"{temperature:.2f}",
   ]
   if cfg.monteCarloSamples > 0:
      args += ["--monte-carlo-samples", str(cfg.monteCarloSamples),
               "--mcts-leaf-batch", str(cfg.mctsLeafBatch),
               "--c-puct", str(cfg.cPuct),
               "-b", str(cfg.generateBatchSize)]
   return runOrion(args, "generate", reportPath)


def trainModel (cfg: Config, inputPath: str, outputPath: str, learningRate: float,
                prevModelPath: Optional[str], reportPath: str) -> Optional[dict]:
   # Precision pinned to fp32: bf16 + small-batch + low-lr was empirically
   # catastrophic (won 6.4% vs random in a controlled experiment), while
   # fp32 / b=256 / lr=0.0003 (this script's defaults) won 83%.
   args = [
      cfg.binary, "train",
      "-i", inputPath,
      "-e", str(cfg.epochs),
      "-b", str(cfg.trainingBatchSize),
      "-o", outputPath,
      "--precision", "fp32",
      "--learning-rate", str(learningRate),
      "--weight-decay", str(cfg.weightDecay),
      "--early-stopping", str(cfg.earlyStopping),
      "--dropout", str(cfg.dropout),
   ]
   if prevModelPath is not None:
      args += ["-m", prevModelPath]
   return runOrion(args, "train", reportPath)


def evaluatePlay (cfg: Config, agentSpecs: list[str], reportPath: str) -> Optional[dict]:
   args = [
      cfg.binary, "play",
      "-n", str(cfg.evalGames),
      "-a", *agentSpecs,
      "-t", f"{cfg.evalTemp:.2f}",
   ]
   return runOrion(args, "play", reportPath)


def generationLearningRate (cfg: Config, gen: int) -> float:
   return cfg.learningRate * (cfg.lrDecay ** (gen - 1))


def computeTemperature (cfg: Config, gen: int) -> float:
   if cfg.maxGenerations <= 1:
      return cfg.finalTemp
   progress = (gen - 1) / (cfg.maxGenerations - 1)
   return cfg.initialTemp - (cfg.initialTemp - cfg.finalTemp) * progress


# ── Path helpers ───────────────────────────────────────────────────────────────

def genStr (cfg: Config, gen: int) -> str:
   width = len(str(cfg.maxGenerations))
   return str(gen).zfill(width)

def modelPath (cfg: Config, gen: int) -> str:
   return f"{cfg.runDir}/models/model_g{genStr(cfg, gen)}_e{cfg.epochs}_b{cfg.trainingBatchSize}"

def dataPath (cfg: Config, gen: int) -> str:
   """Path for data generated by the model at the START of `gen` (the previous
   champion). Generation 1's data is generated by the bootstrap model and labelled g00."""
   return f"{cfg.runDir}/trainingdata/data_g{genStr(cfg, gen - 1)}_{cfg.gamesPerGeneration}"

def reportFile (cfg: Config, gen: int, kind: str) -> str:
   return f"{cfg.runDir}/gen_{genStr(cfg, gen)}_{kind}.json"

def masterFile (cfg: Config) -> str:
   return f"{cfg.runDir}/run.json"


# ── Main loop ──────────────────────────────────────────────────────────────────

def runGeneration (cfg: Config, gen: int, prevModel: str) -> tuple[str, dict]:
   """One self-play generation. Returns (next champion path, generation entry dict for the master record)."""
   temp = computeTemperature(cfg, gen)
   lr = generationLearningRate(cfg, gen)
   print(f"\n=== Generation {gen} (temperature: {temp:.2f}, LR: {lr:.6f}) ===")

   data = dataPath(cfg, gen)
   currentModel = modelPath(cfg, gen)

   print(f"Generating {cfg.gamesPerGeneration} games with {prevModel}...")
   generateReport = generateData(cfg, data, f"{prevModel}/", temp, reportFile(cfg, gen, "generate"))
   if generateReport is None:
      sys.exit(1)

   print(f"Training model (continuing from {prevModel})...")
   trainingInput = f"{cfg.runDir}/trainingdata" if cfg.accumulateData else f"{data}.bin.lz4"
   trainReport = trainModel(cfg, trainingInput, currentModel, lr,
                            prevModelPath=f"{prevModel}/",
                            reportPath=reportFile(cfg, gen, "train"))
   if trainReport is None:
      sys.exit(1)

   print("Evaluating model vs random...")
   evalRandomReport = evaluatePlay(cfg, [f"{currentModel}/", "random"],
                                   reportFile(cfg, gen, "eval_vs_random"))
   if evalRandomReport is None:
      sys.exit(1)

   print("Evaluating model vs heuristic...")
   evalHeuristicReport = evaluatePlay(cfg, [f"{currentModel}/", "heuristic"],
                                      reportFile(cfg, gen, "eval_vs_heuristic"))
   if evalHeuristicReport is None:
      sys.exit(1)

   print(f"Evaluating model vs {prevModel}...")
   evalPrevReport = evaluatePlay(cfg, [f"{currentModel}/", f"{prevModel}/"],
                                 reportFile(cfg, gen, "eval_vs_prev"))
   if evalPrevReport is None:
      sys.exit(1)

   # Champion gating: read win rate directly from the structured report.
   winRateVsPrev = evalPrevReport["results"]["perPlayer"][0]["winRateOverDecisive"]
   accepted = True
   if cfg.championThreshold > 0:
      if winRateVsPrev < cfg.championThreshold:
         print(f"New model win rate {winRateVsPrev:.1%} < threshold {cfg.championThreshold:.1%} — keeping previous champion")
         accepted = False
      else:
         print(f"New model win rate {winRateVsPrev:.1%} >= threshold {cfg.championThreshold:.1%} — accepting new champion")

   genEntry = {
      "generationIndex":   gen,
      "previousModel":     prevModel,
      "trainedModel":      currentModel,
      "temperature":       temp,
      "learningRate":      lr,
      "winRateVsPrev":     winRateVsPrev,
      "championAccepted":  accepted,
      "generate":          generateReport,
      "train":             trainReport,
      "evalVsRandom":      evalRandomReport,
      "evalVsHeuristic":   evalHeuristicReport,
      "evalVsPrev":        evalPrevReport,
   }

   nextChampion = currentModel if accepted else prevModel
   return nextChampion, genEntry


def runFirstGenerationFromData (cfg: Config, dataPath: str) -> tuple[str, dict]:
   """Generation 1 when starting from a data file: skip generation, train from
   scratch on the supplied data, evaluate against random and heuristic (no
   champion to compare to yet)."""
   gen = 1
   lr = generationLearningRate(cfg, gen)
   print(f"\n=== Generation {gen} (training on supplied data, LR: {lr:.6f}) ===")

   currentModel = modelPath(cfg, gen)
   print(f"Training model from scratch on {dataPath}...")
   trainReport = trainModel(cfg, dataPath, currentModel, lr,
                            prevModelPath=None,
                            reportPath=reportFile(cfg, gen, "train"))
   if trainReport is None:
      sys.exit(1)

   print("Evaluating model vs random...")
   evalRandomReport = evaluatePlay(cfg, [f"{currentModel}/", "random"],
                                   reportFile(cfg, gen, "eval_vs_random"))
   if evalRandomReport is None:
      sys.exit(1)

   print("Evaluating model vs heuristic...")
   evalHeuristicReport = evaluatePlay(cfg, [f"{currentModel}/", "heuristic"],
                                      reportFile(cfg, gen, "eval_vs_heuristic"))
   if evalHeuristicReport is None:
      sys.exit(1)

   genEntry = {
      "generationIndex":   gen,
      "previousModel":     None,
      "trainedModel":      currentModel,
      "temperature":       None,        # no generate this generation
      "learningRate":      lr,
      "winRateVsPrev":     None,        # no champion to compare against
      "championAccepted":  True,        # always accepted; it's the first
      "generate":          None,
      "train":             trainReport,
      "evalVsRandom":      evalRandomReport,
      "evalVsHeuristic":   evalHeuristicReport,
      "evalVsPrev":        None,
   }
   return currentModel, genEntry


def configFromArgs (args: dict) -> Config:
   return Config(
      runDir              = args["RUN_DIR"],
      initialModel        = args["--initial-model"],
      initialData         = args["--initial-data"],
      gamesPerGeneration  = int(args["--games-per-generation"]),
      epochs              = int(args["--epochs"]),
      trainingBatchSize   = int(args["--training-batch-size"]),
      generateBatchSize   = int(args["--generate-batch-size"]),
      maxGenerations      = int(args["--generations"]),
      evalGames           = int(args["--eval-games"]),
      championThreshold   = float(args["--champion-threshold"]),
      earlyStopping       = int(args["--early-stopping"]),
      initialTemp         = float(args["--initial-temp"]),
      finalTemp           = float(args["--final-temp"]),
      learningRate        = float(args["--learning-rate"]),
      lrDecay             = float(args["--lr-decay"]),
      weightDecay         = float(args["--weight-decay"]),
      evalTemp            = float(args["--eval-temp"]),
      dropout             = float(args["--dropout"]),
      monteCarloSamples   = int(args["--monte-carlo-samples"]),
      mctsLeafBatch       = int(args["--mcts-leaf-batch"]),
      cPuct               = float(args["--c-puct"]),
      accumulateData      = bool(args["--accumulate-data"]),
      binary              = args["--binary"],
   )


def main ():
   global _command_log
   cfg = configFromArgs(docopt(__doc__))

   # Exactly one of --initial-model / --initial-data must be supplied.
   # docopt enforces this via the (... | ...) grouping in the usage line, but
   # validate the file/directory existence too.
   if cfg.initialModel is not None:
      if not os.path.isdir(cfg.initialModel):
         print(f"Error: --initial-model directory not found: {cfg.initialModel}", file=sys.stderr)
         sys.exit(1)
   elif cfg.initialData is not None:
      if not os.path.exists(cfg.initialData):
         print(f"Error: --initial-data path not found: {cfg.initialData}", file=sys.stderr)
         sys.exit(1)

   os.makedirs(cfg.runDir,                               exist_ok=True)
   os.makedirs(os.path.join(cfg.runDir, "trainingdata"), exist_ok=True)
   os.makedirs(os.path.join(cfg.runDir, "models"),       exist_ok=True)

   _command_log = f"{cfg.runDir}/commands.log"
   with open(_command_log, "w") as f:
      f.write(f"# Orion training run — {datetime.datetime.now().isoformat()}\n")

   master = {
      "schemaVersion":  1,
      "type":           "iterativeRun",
      "runDir":         cfg.runDir,
      "startedAt":      datetime.datetime.now().isoformat(timespec="seconds"),
      "completedAt":    None,
      "config":         asdict(cfg),
      "generations":    [],
   }
   writeJsonAtomic(masterFile(cfg), master)

   # Pick the entry path: model start (gen 1 generates) or data start (gen 1 trains).
   if cfg.initialModel is not None:
      currentModel = cfg.initialModel
      startGen = 1
   else:
      currentModel, genEntry = runFirstGenerationFromData(cfg, cfg.initialData)
      master["generations"].append(genEntry)
      master["completedAt"] = datetime.datetime.now().isoformat(timespec="seconds")
      writeJsonAtomic(masterFile(cfg), master)
      startGen = 2

   for gen in range(startGen, cfg.maxGenerations + 1):
      currentModel, genEntry = runGeneration(cfg, gen, currentModel)
      master["generations"].append(genEntry)
      master["completedAt"] = datetime.datetime.now().isoformat(timespec="seconds")
      writeJsonAtomic(masterFile(cfg), master)

   print(f"\n=== Training complete! Final model: {currentModel} ===")
   print(f"Run report: {masterFile(cfg)}")


if __name__ == "__main__":
   main()
